-- populate_exp_perf_measures_am_cong_mn.sql
UPDATE expressway_performance_measures INNER JOIN Inrix_2019_cmp_exp_cong_min_tmc_am ON expressway_performance_measures.tmc = Inrix_2019_cmp_exp_cong_min_tmc_am.tmc SET expressway_performance_measures.am_cong_mn = [Inrix_2019_cmp_exp_cong_min_tmc_am].[cong_min];
