-- populate_exp_perf_measures_am_del_mi.sql
UPDATE expressway_performance_measures INNER JOIN Inrix_2019_cmp_exp_delay_per_mile_am ON expressway_performance_measures.tmc = Inrix_2019_cmp_exp_delay_per_mile_am.tmc SET expressway_performance_measures.am_del_mi = [Inrix_2019_cmp_exp_delay_per_mile_am].[delay_per_mile];
