-- populate_exp_perf_measures_pm_5ptt_ix.sql
UPDATE expressway_performance_measures INNER JOIN Inrix_2019_cmp_exp_planning_time_idx_pm ON expressway_performance_measures.tmc = Inrix_2019_cmp_exp_planning_time_idx_pm.tmc SET expressway_performance_measures.pm_5ptt_ix = [inrix_2019_cmp_exp_planning_time_idx_pm].[pt_idx];
