-- populate_exp_perf_measures_pm_avtt_ix.sql
UPDATE expressway_performance_measures INNER JOIN Inrix_2019_cmp_exp_travel_time_idx_pm ON expressway_performance_measures.tmc = Inrix_2019_cmp_exp_travel_time_idx_pm.tmc SET expressway_performance_measures.pm_avtt_ix = [Inrix_2019_cmp_exp_travel_time_idx_pm].[tt_idx];
